# This is a basic workflow to help you get started with Actions

name: pushDocs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@main
        
      # 使用的node版本 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
            node-version:  ${{ matrix.node }}
      # Runs a single command using the runners shell
      # 执行安装
      - name: Install dependencies
        run: npm install
        # 执行打包
      - name: Build VitePress
        run: npm run docs:build
      # 执行部署
      # Runs a set of commands using the runners shell
      - name: Deploy to Pages
        run:  |
          cd docs/.vitepress/dist 
          git config --global init.defaultBranch main
          git init
          git config user.name "mayunlongtx"
          git config user.email "${{ secrets.GIT_EMAIL }}"
          git add .
          # git commit -m 'deploy'
          # git branch -m 'main'
          git commit -m "Deploying to gh-pages from @ $GITHUB_SHA in $(date +"%Y年%m月%d日 %T %Z")"
          git push -f https://mayunlongtx:${{ secrets.ACCESS_TOKEN }}@github.com/mayunlongtx/vitepress-test.git main:gh-pages
          cd -
